export const QUERY_KEY = {
    GET_ALL_GENRES: "GET_ALL_GENRES",
    GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
    GET_MOVIE_BY_GENRE: "GET_MOVIE_BY_GENRE",
    GET_MOVIE_BY_TYPE: "GET_MOVIE_BY_TYPE",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
};
