export const QUERY_KEY = {
    GET_ALL_GENRES: "GET_ALL_GENRES",
    GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
    GET_MOVIE_BY_GENRE: "GET_MOVIE_BY_GENRE",
    GET_MOVIE_BY_COUNTRY: "GET_MOVIE_BY_GENRE",
    GET_MOVIE_BY_TYPE: "GET_MOVIE_BY_TYPE",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
    GET_LIST_MOVIES: "GET_LIST_MOVIES",
    GET_SEARCH_MOVIE: "GET_SEARCH_MOVIE",
    GET_FAVORITE_MOVIES: "GET_FAVORITE_MOVIES"
};
